version: '3.8'

# Development version that connects to external backend
services:
  palletten-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: palletten-ui-dev
    env_file:
      - .env
    environment:
      - API_BASE_URL=http://127.0.0.1:9000
      - PYTHONUNBUFFERED=1
    volumes:
      - ./documents:/app/documents:ro
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8504/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s