[project]
name = "palletten-gpt-ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.28.0",
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "PyPDF2>=3.0.0",
    "streamlit-pdf-viewer>=0.0.5"
]
